[pytest]
addopts =
    --alluredir=allure-results
    -v
    --clean-alluredir

markers =
    smoke: critical subset of tests
    regression: full regression suite
    transaction: tests that perform real operations (use with caution)
    exclude: excluded from scheduled runs

log_cli = true
log_cli_level = INFO
